FROM mysql:latest
ENV TZ=Asia/Bangkok
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ENV MYSQL_ROOT_PASSWORD #$%Runner01
ENV MYSQL_USER zenithth
ENV MYSQL_PASSWORD #$%Runner01
ADD database.sql /root
ADD mqttServer.py /root
ADD mysqlConnect.py /root
ADD command.py /root
ADD setup.py /root
ADD setting.json /root
ADD setup.sh /root

RUN apt update
RUN apt install -y python3 python3-pip vim openjdk-11-jre wget
RUN pip3 install paho-mqtt pymysql
RUN wget -P /root https://downloads.metabase.com/v0.40.5/metabase.jar
RUN mysql -u root -p#$%Runner01 < database.sql
RUN javac -jar /root/metabase.jar &
RUN python3 /root/mqttServer.py

EXPOSE 3306
EXPOSE 3000
