FROM debian:latest
ADD DataBase_API/* /root/DataBase_API

RUN apt update
RUN apt install -y python3 python3-pip python3-venv vim bash 
RUN pip3 install django djangorestframework pymysql

EXPOSE 8080
