FROM debian:stable
ENV TZ=Asia/Bangkok
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /root
COPY . .
RUN apt update
RUN apt install -y python3 python3-pip vim net-tools
RUN pip3 install paho-mqtt pymysql[rsa]
CMD python3 /root/mqttServer.py
