FROM mysql:latest
ENV TZ=Asia/Bankok
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
ENV MYSQL_ROOT_PASSWORD yourpassword

COPY ./database.sql /docker-entrypoint-initdb.d/

EXPOSE 3306
